print("Учеными доказано, что существует 6 этапов развития человека")
print("Australopithecus,Homo habilis,Homo erectus,Homo heidelbergensis ,Homo neanderthalensis,Homo sapiens sapiens")
print(" последняя стадия - Homo sapiens sapiens.\n")
a1=input("Australopithecus")
a2=input("Homo habilis")
a3=input("Homo erectus")
a4=input("Homo heidelbergensis")
a5=input("Homo sapiens")
a6=input("Homo sapiens sapiens")
print("\n Последовательность эволюции человека:")
print(a1, a2, a3, a4, a5, a6, sep="=>")